### ISSUE TITLE
Проблема с обновлением

### ISSUE THREAD

**Issue by CrazyBoy49z** [sergant210/siteStatistics#1]
Не работает обновление данного компонента с версии 2.2.1 с modstore

Консоль запущена...
Пробуем установить пакет с подписью: sitestatistics-2.2.2-pl
Пакет найден... сейчас идёт подготовка к его установке.
xPDOZip: Error opening archive at /home/finiv/modx/core/packages/sitestatistics-2.2.2-pl.transport.zip
PHP warning: ZipArchive::extractTo(): Invalid or uninitialized Zip object
PHP warning: ZipArchive::close(): Invalid or uninitialized Zip object
Could not unpack package /home/finiv/modx/core/packages/sitestatistics-2.2.2-pl.transport.zip to /home/finiv/modx/core/packages/. SIG: sitestatistics-2.2.2-pl
Невозможно установить пакет с подписью: sitestatistics-2.2.2-pl

**Comment by sergant210** [comment]
Принято.

**Comment by sergant210** [comment]
Проблема оказалась в битом архиве пакета именно в modstore. Видимо произошёл какой-то сбой при добавлении файла в магазин. В официальном репозитории тот же файл рабочий и ставится без ошибок.
