### ISSUE TITLE
Белый экран

### ISSUE THREAD

**Issue by khpvo** [sergant210/siteStatistics#6]
https://github.com/sergant210/siteStatistics/blob/c5d685779b0c8f268c3971d00fcb2ca4618250b0/core/components/sitestatistics/services/sitestatistics.class.php#L10

MODX Revolution 2.6.5-pl (advanced)
PHP Version:5.3.3

На фронте белый экран:
Parse error: syntax error, unexpected '[' in /var/www/******/data/www/***.ru/core/components/sitestatistics/services/sitestatistics.class.php on line 10

В журнале ошибок:
[2020-09-10 20:52:27] (ERROR @ /var/www/******/data/www/***.ru/core/model/modx/rest/modrestclient.class.php : 241) Could not connect to provider at: https://rest.modx.com/extras/

**Comment by sergant210** [comment]
Версия PHP >= 5.5.
